### ISSUE TITLE
Questions [Code review]

### ISSUE THREAD

**Issue by Walidoux** [SnowTs/snowts.github.io#21]
Hiya!

Since you requested it in Grafikart's Discord server, I've reviewed your code. I reckon there is a lot of stuff going on.

First question:
Why would you choose turbo if this is only dedicated to a SPA (Single Web Application)? You don't have many applications and you don't have like storing structure for heavy-like components that can't be shared across your application, because this is not a mono repo.

Second question (out of curiosity):
How's that possible to have `md` and `mdx` files that can act like `js` and `jsx` files?

**Comment by AugustinMauroy** [comment]
Chose turbo it's just to reduce building time

second we use nextra to build page with md and mdx 

Ref: https://nextra.site

**Comment by Walidoux** [comment]
✨ That's great, I've never heard of `nextra` tbh, this looks promising!
I'm aware you have other bundling tools that can reproduce and might be way better than Turbo such as [SWC](https://swc.rs/) written in Rust, Rollup, Parcel...
As far as I know, Turbo bundles your code depending if the cache has changed compared to the latest build, that's the reason you see `FULL TURBO`

**Comment by AugustinMauroy** [comment]
I will take a look to SWC
